version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL}
    ports:
      - "5173:80"
    env_file:
      - .env

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: gowhere-postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: "redis:7-alpine"
    container_name: ${REDIS_HOST}
    env_file:
      - .env
    ports:
      - "6379:6379"

volumes:
  postgres_data:
