FROM gradle:8.14.3-jdk17-alpine

WORKDIR /app

COPY build.gradle settings.gradle gradlew ./
COPY gradle ./gradle

RUN chmod +x ./gradlew

RUN ./gradlew build -x test --warning-mode all || true

COPY . .

CMD ["./gradlew", "bootRun"]
